# Generated by Django 5.1 on 2024-10-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_recipe_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
