# Generated by Django 5.1 on 2024-11-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedpricepermeal',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='estimatedpricepermeal',
            name='price_to',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
