# Generated by Django 5.1 on 2024-11-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_review_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
