# Generated by Django 5.1 on 2024-10-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_recipe', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
