# Generated by Django 5.1 on 2024-10-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_recipe', '0004_remove_ingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_attributes',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='create_recipe.dietaryattribute'),
        ),
    ]
