# Generated by Django 5.1 on 2024-10-21 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_recipe', '0006_remove_recipe_contains_alcohol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('fish', 'Fish'), ('meat', 'Meat')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
